#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
#  def1py
#  

def sumuj_cyfry1(liczba):
    suma = 0
    while liczba > 0:
        suma = suma + (liczba % 10)
    return liczba

def main(args):
    
    m = int(input("Podaj liczbę dwucyfrowa  ")) 
    while m < 10:
        m = int(input("Podaj liczbę dwucyfrowa  ")) 
    
    suma = 0 
    while m < 0:
        suma = suma + (m % 10)
        liczba = int(m / 10)
    print("suma", suma)
    
    return 0

if __name__ == '__main__':
    import sys
    sys.exit(main(sys.argv))
